### ISSUE TITLE
ContextMenu is not serializable

### ISSUE THREAD

**Issue by mas4ivv** [vaadin/vaadin-context-menu-flow#102]
Simple test case:

```
    @Test
    public void serializeContextMenu() throws IOException {
        Button menuButton = new Button();
        ContextMenu menu = new ContextMenu(menuButton);
        menu.add(new Label());
        ObjectOutputStream out = new ObjectOutputStream(new ByteArrayOutputStream());
        out.writeObject(menu);
    }

```

This test will throw a NotSerializableException. It is caused by MenuItemsArrayGenerator using a Consumer in runBeforeClientResponse. Changing the signature to SerializableConsumer will fix this problem.

**Comment by TatuLund** [comment]
Yes, just pointing out the place in code, this is trivial case

https://github.com/vaadin/vaadin-context-menu-flow/blob/master/vaadin-context-menu-flow/src/main/java/com/vaadin/flow/component/contextmenu/MenuItemsArrayGenerator.java#L102
