### ISSUE TITLE
OSGi: ERROR: bundle com.vaadin.flow.component.contextmenu:1.2.1 (77)Component descriptor entry 'OSGI-INF/com.vaadin.flow.component.contextmenu.osgi.ContextMenuConectorResource.xml' not found

### ISSUE THREAD

**Issue by enver-haase** [vaadin/vaadin-context-menu-flow#39]
ERROR: bundle com.vaadin.flow.component.contextmenu:1.2.1 (77)Component descriptor entry 'OSGI-INF/com.vaadin.flow.component.contextmenu.osgi.ContextMenuConectorResource.xml' not found

when starting up the base-starter-flow-osgi

**Comment by pleku** [comment]
Fixed with https://github.com/vaadin/flow-component-base/issues/116 since 12.0.3
