### ISSUE TITLE
Context Menu not working after page change

### ISSUE THREAD

**Issue by Tonne-TM** [vaadin/vaadin-context-menu-flow#47]
I came across a strange problem with context menu component (Vaadin 12.0.5).

In my usecase i have 2 pages under a main layout. On page 1 i have a context menu. The bug happens when i do the following:

1. Navigate to page 1 (context menu is working fine)
2. Navigate to Page 2
3. Navigate back to Page 1 (context menu not working)

When i am back on Page 1 the context menu is not showing at all and no error is thrown. My workaround for this usecase::

    myContextMenu.addAttachListener(a -> myContextMenu.setTarget(myButton));
    

(Original https://vaadin.com/forum/thread/17512874/17518460)

**Comment by pekam** [comment]
Hi!
I couldn't reproduce the issue with the provided information.

I create and attach the context menu in the constructor of the first page. When I navigate back to this page, the constructor gets called and sets up everything like it should.

Am I missing something? Where are you constructing the context menu in your code? Are you perhaps using a `PolymerTemplate`?

If you could provide a minimal code snippet to reproduce the issue, that would be great!

**Comment by mas4ivv** [comment]
We are facing the same problem. The difference to your test case is, we are not running the constructor again. I reproduced the issue with a fresh bookstoreexample with these changes:

- changing barAndGridLayout to an instance var:

    private VerticalLayout barAndGridLayout = new VerticalLayout();

- modified createTopBar:
`    public HorizontalLayout createTopBar() {
        HorizontalLayout topLayout = new HorizontalLayout();
        this.filter = new TextField();
        this.filter.setPlaceholder("Filter name, availability or category");
        // Apply the filter to grid's data provider. TextField value is never null
        this.filter.addValueChangeListener(event -> this.dataProvider.setFilter(event.getValue()));
        this.filter.addFocusShortcut(Key.KEY_F, KeyModifier.CONTROL);

        this.newProduct = new Button("New product");
        ContextMenu ctxMenu = new ContextMenu(this.newProduct);
        ctxMenu.addItem("One", e -> {
            this.barAndGridLayout.remove(topLayout);
            final Button button = new Button("Back");
            button.addClickListener(click -> {
                this.remove(button);
                this.barAndGridLayout.add(topLayout);
            });
            this.add(button);
        });
        ctxMenu.addItem("Two");
        ctxMenu.setOpenOnClick(true);

        this.newProduct.addThemeVariants(ButtonVariant.LUMO_PRIMARY);
        this.newProduct.setIcon(VaadinIcon.PLUS_CIRCLE.create());
        //        this.newProduct.addClickListener(click -> this.viewLogic.newProduct());
        // CTRL+N will create a new window which is unavoidable
        this.newProduct.addClickShortcut(Key.KEY_N, KeyModifier.ALT);

        topLayout.setWidth("100%");
        topLayout.add(this.filter);
        topLayout.add(this.newProduct);
        topLayout.setVerticalComponentAlignment(Alignment.START, this.filter);
        topLayout.expand(this.filter);
        return topLayout;
    }`

Now you can select "One" from the context menu of the newProduct button, which will hide this button. Pressing "Back" puts the topBar back into the layout (though at the bottom). When you press the button now, there is no context menu showing.

**Comment by pekam** [comment]
Ok, so this is actually not about navigating between pages. The bug occurs when the target is removed and re-attached.
