### ISSUE TITLE
Context menu broken after removing and re-adding its target

### ISSUE THREAD

**Issue by eriklumme** [vaadin/vaadin-context-menu-flow#49]
If the target of the context menu is removed from the page, and later re-added, the context menu no longer works and its connector is missing.

Example

    Button contextButton = new Button("Open context menu");

    ContextMenu contextMenu = new ContextMenu();
    contextMenu.setTarget(contextButton);
    contextMenu.addItem("Click me", e -> {});
    contextMenu.setOpenOnClick(true);

    Button destroyButton = new Button("Toggle context menu button");
    destroyButton.addClickListener(e -> {
        if (indexOf(contextButton) != -1) {
            remove(contextButton);
        } else {
            add(contextButton);
        }
    });

    Button updateButton = new Button("Update context menu");
    updateButton.addClickListener(e -> {
        contextMenu.setOpenOnClick(true);
    });

    add(destroyButton, updateButton, contextButton);

The `contextButton` shows the context menu on click. After removing and adding the button using the  `Toggle context menu button` button, the context menu is no longer opened when it is clicked. In addition, updating the context menu using the update button throws an error in the client, as the connector is missing.

**Comment by eriklumme** [comment]
The reason seems to be that naturally, as the element is removed and re-attached on the client, the connector association is removed.

One could otherwise set the target again, but as it already has a target, it will try calling `$contextMenuConnector.removeConnector` first, which fails as `$contextMenuConnector` is undefined.

Making that thing conditional on `$contextMenuConnector` being present makes the workaround simpler, but ideally, the connector would be re-attached automatically.

**Comment by pekam** [comment]
Fixed by #55
