### ISSUE TITLE
It is not possible to change overlay position when in small screens.

### ISSUE THREAD

**Issue by Klaudeta** [vaadin/vaadin-context-menu-flow#61]
When context-menu is opened on small screens ( less than 420px of width) it is displayed on the bottom of the screen. 

There is no easy way of customizing the context-menu position. 

A better expected behavior would be to have its position configurable from the API. 
Something similar to:

```
ContextMenu.displayAt(Position.CLICKED); 
```

where position is an enum (CLICKED, TOP, BOTTOM, LEFT, RIGHT)

**Comment by web-padawan** [comment]
This is by design. We use the same appearance also for `vaadin-select` on mobile.

**Comment by web-padawan** [comment]
Closing per above comment as working as intended.
