### ISSUE TITLE
Long press not working on mobile

### ISSUE THREAD

**Issue by Francesco-Margiotta-Casaluci** [vaadin/vaadin-context-menu-flow#88]
Long press event not working for opening context view on mobile devices

**Comment by pekam** [comment]
Hi! Could you try if you can still reproduce the issue with Vaadin `14.0.0.rc5`? I can't reproduce this on my own, but the latest release should contain a fix for context menu not opening in some conditions.

**Comment by tomivirkki** [comment]
Closing as inactive
